name: install

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [master]
env:
    GO_VERSION: '1.20'

jobs:
  install_go_get:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
            go-version: "^${{ env.GO_VERSION }}"

      - name: Install
        shell: bash 
        run: |
          set +x
          go mod init test
          go get github.com/moment-technology/goka@master
          cat > main.go << EndOfMessage
          package main

          import (
            "context"

            "github.com/moment-technology/goka"
          )
          func main() {
            proc, _ := goka.NewProcessor(nil, goka.DefineGroup("test"))
            proc.Run(context.Background())
          }
          EndOfMessage
          cat main.go
          go mod tidy
          cat go.mod
          echo "Compiling module"
          go build -v .
          echo "... done"
          
