name: run tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
env:
    GO_VERSION: '1.20'

jobs:
  unit:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
            go-version: "^${{ env.GO_VERSION }}"

      - name: Test
        shell: bash
        run: |
          go test -v -race ./...

  system-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
            go-version: "^${{ env.GO_VERSION }}"

      - name: Services
        shell: bash
        run: |
          sudo apt update -y && sudo apt install -y netcat
          cd examples && make start && cd ..

      - name: Test
        shell: bash
        run: |
          GOKA_SYSTEMTEST=y go test -v github.com/moment-technology/goka/systemtest

          
